In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dt=pd.read_csv("Downloads/cancer.csv")
dt.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [43]:
#checking for null values
dt.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
df=pd.get_dummies(dt)
del df['Unnamed: 32']
del df['diagnosis_B']
df['diagnosis_M']
df.iloc[:,31]

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     0
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
539    0
540    0
541    0
542    0
543    0
544    0
545    0
546    0
547    0
548    0
549    0
550    0
551    0
552    0
553    0
554    0
555    0
556    0
557    0
558    0
559    0
560    0
561    0
562    1
563    1
564    1
565    1
566    1
567    1
568    0
Name: diagnosis_M, Length: 569, dtype: uint8

In [60]:
#seperating target variable as 'y'
X=df.iloc[:,1:31]
y=df.iloc[:,31]
y

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      1
10     1
11     1
12     1
13     1
14     1
15     1
16     1
17     1
18     1
19     0
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     1
28     1
29     1
      ..
539    0
540    0
541    0
542    0
543    0
544    0
545    0
546    0
547    0
548    0
549    0
550    0
551    0
552    0
553    0
554    0
555    0
556    0
557    0
558    0
559    0
560    0
561    0
562    1
563    1
564    1
565    1
566    1
567    1
568    0
Name: diagnosis_M, Length: 569, dtype: uint8

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=10)

In [8]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()

In [9]:
#training model
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [10]:
predict=model.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
accuracy_score(y_test,predict)

0.9005847953216374

In [12]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       0.94      0.90      0.92       112
           1       0.83      0.90      0.86        59

   micro avg       0.90      0.90      0.90       171
   macro avg       0.89      0.90      0.89       171
weighted avg       0.90      0.90      0.90       171

In [13]:
print(confusion_matrix(y_test,predict))

[[101  11]
 [  6  53]]

In [59]:
# comparing predicted values and actual test values
ast=pd.DataFrame({'pred':predict,'test':y_test})
ast

     pred  test
172     1     1
553     0     0
374     0     0
370     1     1
419     0     0
152     0     0
550     0     0
92      0     0
264     1     1
214     1     1
69      0     0
418     0     0
47      1     1
439     0     0
566     1     1
253     1     1
463     0     0
377     1     0
102     0     0
491     0     0
329     0     1
194     1     1
459     0     0
227     0     0
433     1     1
282     1     1
466     0     0
533     1     1
289     0     0
228     0     0
..    ...   ...
59      0     0
164     1     1
327     0     0
60      0     0
260     1     1
504     0     0
544     0     0
367     0     0
139     0     0
119     1     1
226     0     0
499     1     1
456     0     0
307     0     0
394     0     0
129     1     1
425     0     0
61      0     0
10      0     1
81      1     0
299     0     0
310     0     0
398     0     0
50      0     0
34      1     1
108     1     1
458     0     0
173     0     0
240     0     0
436     0     0

[171 rows x 2 columns]

print(str(y)+"   ,   "+str(y_test))